name : PlaywriteFramework

on:
 push:
  branches:[ main ]

jobs:
 Demo1:
  runs-on:ubuntu-latest

    steps:
      -name : checkout-repo
       uses : actions/checkout@v4

      -name : Setup node.js
       uses:actions/setup-node@v4
       with:
        node-version: 18

      -name : Install Dependencies
       run : npm ci

      -name : Run Cucumber tests
       run : npm test
       env :
         CI: true

      -name : Generate HTML report
       if : always()
       run : npm run report

      -name : Upload Cucumber report
       if : always()
       uses : actions/upload-artifact@v4
       with : 
         name : cucumber-report
         path : reports

      

  
